# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wo7V5XV4pEzOcgRdFJMVpUJ2F674hxJP
"""

import streamlit as st
import joblib
import pandas as pd


# =========================================================
# PAGE CONFIGURATION
# =========================================================

st.set_page_config(
    page_title="Malaysia Housing Price Predictor",
    page_icon="🏠",
    layout="centered"
)


# =========================================================
# LOAD DATASET
# =========================================================

@st.cache_data
def load_data():
    return pd.read_csv("malaysia_house_price_data_2025_cleaned.csv")


df = load_data()


# =========================================================
# GET CATEGORICAL VALUES
# =========================================================

states = sorted(
    df["State"].dropna().unique().tolist()
)

tenures = sorted(
    df["Tenure"].dropna().unique().tolist()
)

property_types = sorted(
    df["Type"].dropna().unique().tolist()
)


# =========================================================
# LOAD TRAINED MODELS
# =========================================================

@st.cache_resource
def load_models():
    return joblib.load("malaysia_house_price_models.joblib")


model_bundle = load_models()

preprocessor = model_bundle["preprocessor"]
models = model_bundle["models"]
metrics = model_bundle["metrics"]

# =========================================================
# MAIN PAGE
# =========================================================

st.title("Malaysia Housing Price Predictor")

st.write(
    "This application predicts the median property price "
    "of residential properties in Malaysia using four "
    "machine-learning regression models: Linear Regression, "
    "Decision Tree, Random Forest, and Gradient Boosting."
)

st.write(
    "Enter the property information below and select a "
    "machine-learning model to obtain an estimated median price."
)


# =========================================================
# MODEL SELECTION
# =========================================================

st.header("Select Machine Learning Model")

selected_model = st.selectbox(
    "Choose a model:",
    [
        "Linear Regression",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting"
    ]
)

st.info(
    f"Selected model: **{selected_model}**"
)


# =========================================================
# PROPERTY INFORMATION
# =========================================================

st.header("🏡 Property Information")

st.write(
    "Please provide the following property details:"
)


# =========================================================
# STATE AND AREA RELATIONSHIP
# =========================================================

# Initial State
if "selected_state" not in st.session_state:
    st.session_state.selected_state = states[0]


# Get areas for the initial state
initial_areas = sorted(
    df.loc[
        df["State"] == st.session_state.selected_state,
        "Area"
    ].dropna().unique().tolist()
)


# Initial Area
if "selected_area" not in st.session_state:
    if initial_areas:
        st.session_state.selected_area = initial_areas[0]
    else:
        st.session_state.selected_area = ""


# ---------------------------------------------------------
# When State changes, update Area
# ---------------------------------------------------------

def update_area_from_state():

    selected_state = st.session_state.selected_state

    available_areas = sorted(
        df.loc[
            df["State"] == selected_state,
            "Area"
        ].dropna().unique().tolist()
    )

    if available_areas:
        st.session_state.selected_area = available_areas[0]


# ---------------------------------------------------------
# When Area changes, update State
# ---------------------------------------------------------

def update_state_from_area():

    selected_area = st.session_state.selected_area

    matching_states = (
        df.loc[
            df["Area"] == selected_area,
            "State"
        ]
        .dropna()
        .unique()
        .tolist()
    )

    if matching_states:
        st.session_state.selected_state = matching_states[0]


# =========================================================
# STATE DROPDOWN
# =========================================================

state = st.selectbox(
    "State",
    states,
    key="selected_state",
    on_change=update_area_from_state
)


# =========================================================
# AREA DROPDOWN
# =========================================================

filtered_areas = sorted(
    df.loc[
        df["State"] == state,
        "Area"
    ].dropna().unique().tolist()
)


# Make sure selected Area belongs to selected State
if filtered_areas:

    if st.session_state.selected_area not in filtered_areas:
        st.session_state.selected_area = filtered_areas[0]

else:

    st.session_state.selected_area = ""


area = st.selectbox(
    "Area",
    filtered_areas,
    key="selected_area",
    on_change=update_state_from_area
)


# =========================================================
# TENURE
# =========================================================

tenure = st.selectbox(
    "Tenure",
    tenures
)


# =========================================================
# PROPERTY TYPE
# =========================================================

property_type = st.selectbox(
    "Property Type",
    property_types
)


# =========================================================
# MEDIAN PSF
# =========================================================

median_psf = st.number_input(
    "Median Price Per Square Foot (RM)",
    min_value=38.0,
    max_value=1045.0,
    value=300.0,
    step=1.0
)


# =========================================================
# TRANSACTIONS
# =========================================================

transactions = st.number_input(
    "Number of Transactions",
    min_value=10,
    max_value=76,
    value=20,
    step=1
)


# =========================================================
# PREDICTION
# =========================================================

st.divider()

st.header("💰 Price Prediction")

col1, col2, col3 = st.columns([1, 2, 1])

with col2:
    predict_button = st.button(
        "💰 Predict Median Price",
        use_container_width=True
    )

if predict_button:

    # -----------------------------------------------------
    # Create input data
    # -----------------------------------------------------

    input_data = pd.DataFrame({
        "Area": [area],
        "State": [state],
        "Tenure": [tenure],
        "Type": [property_type],
        "Median_PSF": [median_psf],
        "Transactions": [transactions]
    })


    # -----------------------------------------------------
    # Get selected model
    # -----------------------------------------------------
    
    model = models[selected_model]
    
    
    # -----------------------------------------------------
    # Apply preprocessing
    # -----------------------------------------------------
    
    input_processed = preprocessor.transform(input_data)
    
    
    # -----------------------------------------------------
    # Make prediction
    # -----------------------------------------------------
    
    prediction = model.predict(input_processed)[0]

    # -----------------------------------------------------
    # Display prediction
    # -----------------------------------------------------

    st.success(
        f"Estimated Median Property Price: "
        f"RM {prediction:,.2f}"
    )


    # -----------------------------------------------------
    # Display selected model
    # -----------------------------------------------------

    st.write(
        f"**Model used:** {selected_model}"
    )
