# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wo7V5XV4pEzOcgRdFJMVpUJ2F674hxJP
"""

import streamlit as st
import pandas as pd
import joblib

# ==========================================
# PAGE CONFIGURATION
# ==========================================

st.set_page_config(
    page_title="Malaysia Housing Price Predictor",
    page_icon="🏠",
    layout="centered"
)

# ==========================================
# LOAD DATASET
# ==========================================

@st.cache_data
def load_data():
    return pd.read_csv("malaysia_house_price_data_2025.csv")


# ==========================================
# LOAD MODELS
# ==========================================

@st.cache_resource
def load_models():
    return joblib.load("housing_models.joblib")


# ==========================================
# LOAD FILES
# ==========================================

df = load_data()
model_bundle = load_models()

models = model_bundle["models"]
metrics = model_bundle["metrics"]


# ==========================================
# APP
# ==========================================

st.title("🏠 Malaysia Housing Price Predictor")

st.write(
    "This application predicts the median property price "
    "of residential properties in Malaysia using four "
    "machine-learning regression models."
)

st.success("Dataset and models loaded successfully!")

# Dataset information
st.subheader("Dataset")

st.write(f"Number of records: {len(df)}")
st.write(f"Number of variables: {len(df.columns)}")

# Model information
st.subheader("Available Models")

for model_name in models:
    st.write(f"• {model_name}")

# Preview
st.subheader("Dataset Preview")

st.dataframe(df.head())